const jwt = require('jsonwebtoken');
const config = require('../config/app');
const logger = require('../utils/logger');
const User = require('../models/User');

/**
 * Token validation middleware
 * Validates JWT tokens generated by API Gateway
 */
async function validateToken(req, res, next) {
  try {
    // Get token from headers
    const authHeader = req.headers['x-auth-token'] || req.headers['authorization'];
    
    if (!authHeader) {
      return res.status(401).json({
        success: false,
        message: 'Authentication token required'
      });
    }

    // Extract token
    const token = authHeader.startsWith('Bearer ') 
      ? authHeader.slice(7) 
      : authHeader;

    // Verify JWT token
    try {
      const decoded = jwt.verify(token, config.jwt.secret);
      
      // Get user from database
      const user = await User.findById(decoded.userId);
      
      if (!user) {
        return res.status(401).json({
          success: false,
          message: 'User not found'
        });
      }

      // Check if user is active
      if (user.status !== 'active') {
        return res.status(403).json({
          success: false,
          message: 'User account is not active'
        });
      }

      // Attach user info to request
      req.user = {
        id: user._id.toString(),
        userId: user._id.toString(),
        iam_uuid: user.iam_uuid,
        email: user.getDecryptedEmail(),
        mobile_number: user.getDecryptedMobile(),
        role_id: user.role_id?.toString(),
      };
      req.token = token;
      
      return next();
    } catch (error) {
      if (error.name === 'JsonWebTokenError') {
        return res.status(401).json({
          success: false,
          message: 'Invalid token'
        });
      }
      if (error.name === 'TokenExpiredError') {
        return res.status(401).json({
          success: false,
          message: 'Token expired'
        });
      }
      throw error;
    }
  } catch (error) {
    logger.error('Token validation error:', error);
    return res.status(500).json({
      success: false,
      message: 'Authentication error'
    });
  }
}

/**
 * Optional token validation - doesn't fail if no token
 */
async function optionalTokenValidation(req, res, next) {
  try {
    const authHeader = req.headers['x-auth-token'] || req.headers['authorization'];
    
    if (authHeader) {
      const token = authHeader.startsWith('Bearer ') 
        ? authHeader.slice(7) 
        : authHeader;

      try {
        const decoded = jwt.verify(token, config.jwt.secret);
        const user = await User.findById(decoded.userId);

        if (user && user.status === 'active') {
          req.user = {
            id: user._id.toString(),
            userId: user._id.toString(),
            iam_uuid: user.iam_uuid,
            email: user.getDecryptedEmail(),
            mobile_number: user.getDecryptedMobile(),
            role_id: user.role_id?.toString(),
          };
          req.token = token;
        }
      } catch (error) {
        // Ignore errors for optional auth
      }
    }
    
    next();
  } catch (error) {
    next();
  }
}

module.exports = {
  validateToken,
  optionalTokenValidation
};

